config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :spots
  resources :favorites
  resources :categories
  resources :foods
  resources :reviews, except: [:index, :create]
  resources :foodies, only: [:show, :new, :create, :destroy]

  get "/foods/:id/newreview", to:"reviews#new", :as => "new_food_review"
  get "/foods/:id/reviews", to:"reviews#index", :as => "food_reviews"
  post "/foods/:id", to:"reviews#create"


  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # get "reviews/:id", to:"reviews#show", :as => "food_review"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
  has_many :locations, through: :foods
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :foodie
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :reviews
  has_many :favorites
  belongs_to :category
  belongs_to :location
  has_many :foodies, through: :reviews
  has_many :foodies, through: :favorites
  has_one_attached :image

  def self.search(search)
    if search
      category = Category.find_by(name: search)
      if category
        self.where(category_id: category)
      else
        Food.all
      end
    else
      Food.all
    end
  end

  def avg_rating
    ratings = self.reviews.map do |r|
      r.rating
  end
    ratings.inject(:+) / ratings.length
  end

end

app/models/foodie.rb
class Foodie < ApplicationRecord
  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true

  has_many :reviews
  has_many :favorites
  has_many :foods, through: :reviews
  has_many :foods, through: :favorites
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :foods
  has_many :categories, through: :foods
end

app/models/review.rb
class Review < ApplicationRecord
  validates :foodie_id, presence: true
  belongs_to :foodie
  belongs_to :food

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show]


  def index
    @categories = Category.all
    @reviews = Review.all

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
  end

  def show
    @foods = @category.foods
  end



  private
  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/foodies_controller.rb
class FoodiesController < ApplicationController

  def show
      @foodie = Foodie.find(params[:id])
    end

    def new
      @foodie = Foodie.new
    end

    def create
      @foodie = Foodie.create(sign_up_params)
      if @foodie.valid?
        session[:foodie_id] = @foodie.id
        redirect_to foods_path
      else
        flash[:errors] = @foodie.errors.full_messages
        redirect_to new_foodie_path
      end
    end

    def destroy
      @foodie = Foodie.find(params[:id])
      @foodie.destroy
      flash[:notice] = 'You deleted your account :('
      redirect_to new_foodie_path
    end


      private

      def sign_up_params
        params.require(:foodie).permit(:username, :password)
      end



end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.search(params[:search])
    @reviews = Review.all
  end

  def new
    @food = Food.new
    @locations = Location.all
    @categories = Category.all
  end

  def create
    @food = Food.create(food_params)
    @food.image.attach(params[:food][:image])
    # @review = Review.create(title: "I need a title", content: "I need content", rating: 0, food_id: @food.id, foodie_id: 1).image.attach(io: File.open('/Users/naomikatz/Desktop/donut.jpeg'), filename: 'donut.jpeg')
    redirect_to new_food_review_path(@food)
  end

  def show

  end

  def edit
    @locations = Location.all
    @categories = Category.all
  end

  def update
    @food.update(food_params)
    redirect_to food_path(@food)
  end


  def destroy
    @food.destroy

  end

  private
  def find_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :spot_name, :address, :location_id, :category_id, :like_count, :search, :image)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location only: :show

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    redirect_to locations_path
  end

private

def find_location
  @location = Location.find(params[:id])
end

def location_params
  params.require(:location).permit(:state, :city)
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :edit, :update, :destroy]

  def index
    @food = Food.find(params[:id])
    @review = @food.reviews

  end

  def show
    @food = @review.food
  end

  def new
    @food = Food.find(params[:id])
    @review = Review.new
    @categories = Category.all
    @locations = Location.all
    @foodies = Foodie.all
  end

  def create
    @food = Food.find(params[:id])
    @review = Review.create(review_params)
    if @review.save
      flash[:success] = "Your review has been created!"
      redirect_to food_path(@food)
    else
      flash[:alert] = "Your review couldn't be created, please check the form."
      render :new
    end
  end

  def edit
    @food = @review.food
    @foodies = Foodie.all
  end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy

    @review.destroy
    redirect_to foods_path
  end

  private
  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating, :food_id, :foodie_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
    render :new #looks in app/views/sessions/new.html.erb
  end


  def create #handles the POST request to /login
    # find out if we have a user with this username

    @foodie = Foodie.find_by(username: params[:username])

    # get that user record from DB
    # authenticate this user; determine if they provided the correct pw

    if @foodie && @foodie.authenticate(params[:password])
      # once we have found the user, create a new session for them
      session[:foodie_id] = @foodie.id
      # redirect_to user_path(@user)
      redirect_to foods_path

    else
      flash[:notice] = 'Invalid username or password'
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:foodie_id)
    # session[:user_id] = nil
    flash[:notice] = 'You have logged out'
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_foodie
    # User.find would throw an error if we cannot find the user
    Foodie.find_by({ id: session[:foodie_id] })
  end

  def logged_in?
    # nil is falsey in ruby
    # a user instance is truthy
    !!current_foodie
  end

  def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/foodies_helper.rb
module FoodiesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/foodies/new.erb
<div class="ui raised very padded text container segment">

<% if flash[:errors] %>
  <% flash[:errors].each do |err| %>
    <%= err %>
    <% end %>
<% end %>

<h4><%= flash[:notice] %></h4>


            <h2> Sign Up </h2>
            <%= form_for @foodie, html: {class: 'ui form'} do |f| %>
            <div class="field">
              <label>Username</label>
              <%= f.text_field :username, placeholder: 'Username'  %>
            </div>

            <div class='field'>
              <label>Password</label>
             <%= f.password_field :password, placeholder: 'Password'  %>
            </div>
            <%= f.submit "Sign Up", class: 'ui black button' %>
           <% end %>
            </div>

app/views/foodies/show.erb
<h1> Hey <%= @foodie.username %> </h1>

<%= button_to 'Logout', logout_path, method: :delete %>

<p><%= @foodie.username %></p>

<% if current_foodie.id == @foodie.id %>
  <%= button_to 'Delete this Account', foodie_path(@foodie), method: :delete, data: { confirm: 'are u sure lol' } %>
<% end %>

app/views/reviews/edit.erb
<div class="ui raised very padded text container segment">

<h1>Edit a Review</h1>

<%= form_for @review, html: {class: 'ui form'} do |f| %>
  <div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  </div>
  <div class="field">
  <%= f.label :rating %>
  <%= f.number_field :rating, class: :number_field, step: :any %><br>
  </div>
  <div class="field">
  <%= f.label :content %>
  <%= f.text_area :content %><br>
  </div>
  <div class="field">
  <%= f.label :foodie %>
  <%= f.collection_select :foodie_id, @foodies, :id, :username, prompt: true %><br>
  </div>
  <%= f.submit class: 'ui black button' %>

<% end %>

app/views/reviews/index.erb
<h1><%=@food.name%></h1>
<%@food.reviews.each do |r|%>
<%=r.title%><br>
<%=r.content%><br>
<%=r.rating%><br>
<%=link_to r.foodie.username, foodie_path(@foodie)%><br>
<%end%>

app/views/reviews/new.erb
<div class="ui raised very padded text container segment">

<h1>Make a Review</h1>

<%= form_for @review, :url => food_path(@food), html: {class: 'ui form'} do |f| %>
  <div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  </div>
  <div class="field">
  <%= f.label :rating %>
  <%= f.number_field :rating, class: :number_field, step: :any %><br>
  </div>
  <div class="field">
  <%= f.label :content %>
  <%= f.text_area :content %><br>
  <%= f.hidden_field(:foodie_id, :value => current_foodie.id)%><br>
  <%= f.hidden_field(:food_id, :value => @food.id)%>
  </div>
  <%= f.submit class: 'ui black button' %>

<% end %>

app/views/reviews/newreview.erb
<h1>Make a Review</h1>

<%= form_for @review, :url => food_reviews_path(@food) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :rating %>
  <%= f.number_field :rating, class: :text_field, step: :any %><br>
  <%= f.label :content %>
  <%= f.text_area :content %><br>
  <%= f.label :foodie %>
  <%= f.collection_select :foodie_id, @foodies, :id, :username, prompt: true %><br>
  <%= f.submit %>

<% end %>

app/views/reviews/show.erb
<div class='ui cards container'>
  <div class="ui raised link card">
    <div class="content">
      <div class="header">
<%= @review.title %><br></div>
  <div class="meta">
<span class="category"><%= @review.food.category.name %><br></span>
</div>
<div class="description"><%= @review.food.name %><br>
  </div>
<%= @review.food.spot_name %><br>
<%= @review.rating %><br>
<%= @review.content %><br></div>


<% if @review.foodie.id == current_foodie.id %>
  <div class="text-center edit-links">
    <%= button_to "Edit Review", edit_review_path(@review), method: 'get', class: 'ui black button mini' %>
    <%= button_to "delete", @review, method: :delete, class: 'ui black button mini', data: {confirm: "Are you sure you want to delete?"} %>
  </div>
<% end %>
<div class="extra content">
  <div class="right floated">
<%= @review.foodie.username %>
</div>
</div>
</div>