config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :spots
  resources :favorites
  resources :categories
  resources :foods
  resources :reviews, except: [:index, :create]
  resources :foodies, only: [:show, :new, :create, :destroy]

  get "/foods/:id/newreview", to:"reviews#new", :as => "new_food_review"
  get "/foods/:id/reviews", to:"reviews#index", :as => "food_reviews"
  post "/foods/:id", to:"reviews#create"


  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # get "reviews/:id", to:"reviews#show", :as => "food_review"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
  has_many :locations, through: :foods
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :foodie
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :reviews
  has_many :favorites
  belongs_to :category
  belongs_to :location
  has_many :foodies, through: :reviews
  has_many :foodies, through: :favorites
  has_one_attached :image

  def self.search(search)
    if search
      category = Category.find_by(name: search)
      if category
        self.where(category_id: category)
      else
        Food.all
      end
    else
      Food.all
    end
  end

  def avg_rating
    ratings = self.reviews.map do |r|
      r.rating
  end
    ratings.inject(:+) / ratings.length
  end

end

app/models/foodie.rb
class Foodie < ApplicationRecord
  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true

  has_many :reviews
  has_many :favorites
  has_many :foods, through: :reviews
  has_many :foods, through: :favorites
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :foods
  has_many :categories, through: :foods
end

app/models/review.rb
class Review < ApplicationRecord
  validates :foodie_id, presence: true
  belongs_to :foodie
  belongs_to :food

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authorized, except: [:create, :new] #lock down this whole app
  helper_method :current_foodie #i can call current_user from a view

  def current_foodie
    # User.find would throw an error if we cannot find the user
    Foodie.find_by({ id: session[:foodie_id] })
  end

  def logged_in?
    # nil is falsey in ruby
    # a user instance is truthy
    !!current_foodie
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show]


  def index
    @categories = Category.all
    @reviews = Review.all

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
  end

  def show
    @foods = @category.foods
  end



  private
  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/foodies_controller.rb
class FoodiesController < ApplicationController

  def show
      @foodie = Foodie.find(params[:id])
    end

    def new
      @foodie = Foodie.new
    end

    def create
      @foodie = Foodie.create(sign_up_params)
      if @foodie.valid?
        session[:foodie_id] = @foodie.id
        redirect_to foods_path
      else
        flash[:errors] = @foodie.errors.full_messages
        redirect_to new_foodie_path
      end
    end

    def destroy
      @foodie = Foodie.find(params[:id])
      @foodie.destroy
      flash[:notice] = 'You deleted your account :('
      redirect_to new_foodie_path
    end


      private

      def sign_up_params
        params.require(:foodie).permit(:username, :password)
      end



end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.search(params[:search])
    @reviews = Review.all
  end

  def new
    @food = Food.new
    @locations = Location.all
    @categories = Category.all
  end

  def create
    @food = Food.create(food_params)
    @food.image.attach(params[:food][:image])
    # @review = Review.create(title: "I need a title", content: "I need content", rating: 0, food_id: @food.id, foodie_id: 1).image.attach(io: File.open('/Users/naomikatz/Desktop/donut.jpeg'), filename: 'donut.jpeg')
    redirect_to new_food_review_path(@food)
  end

  def show

  end

  def edit
    @locations = Location.all
    @categories = Category.all
  end

  def update
    @food.update(food_params)
    redirect_to food_path(@food)
  end


  def destroy
    @food.destroy

  end

  private
  def find_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :spot_name, :address, :location_id, :category_id, :like_count, :search, :image)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location only: :show

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    redirect_to locations_path
  end

private

def find_location
  @location = Location.find(params[:id])
end

def location_params
  params.require(:location).permit(:state, :city)
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :edit, :update, :destroy]

  def index
    @food = Food.find(params[:id])
    @review = @food.reviews

  end

  def show
    @food = @review.food
  end

  def new
    @food = Food.find(params[:id])
    @review = Review.new
    @categories = Category.all
    @locations = Location.all
    @foodies = Foodie.all
  end

  def create
    @food = Food.find(params[:id])
    @review = Review.create(review_params)
    if @review.save
      flash[:success] = "Your review has been created!"
      redirect_to food_path(@food)
    else
      flash[:alert] = "Your review couldn't be created, please check the form."
      render :new
    end
  end

  def edit
    @food = @review.food
    @foodies = Foodie.all
  end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy

    @review.destroy
    redirect_to foods_path
  end

  private
  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating, :food_id, :foodie_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
    render :new #looks in app/views/sessions/new.html.erb
  end


  def create #handles the POST request to /login
    # find out if we have a user with this username

    @foodie = Foodie.find_by(username: params[:username])

    # get that user record from DB
    # authenticate this user; determine if they provided the correct pw

    if @foodie && @foodie.authenticate(params[:password])
      # once we have found the user, create a new session for them
      session[:foodie_id] = @foodie.id
      # redirect_to user_path(@user)
      redirect_to foods_path

    else
      flash[:notice] = 'Invalid username or password'
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:foodie_id)
    # session[:user_id] = nil
    flash[:notice] = 'You have logged out'
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_foodie
    # User.find would throw an error if we cannot find the user
    Foodie.find_by({ id: session[:foodie_id] })
  end

  def logged_in?
    # nil is falsey in ruby
    # a user instance is truthy
    !!current_foodie
  end

  def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/foodies_helper.rb
module FoodiesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/categories/index.erb
<h1>Categories</h1>
<% @categories.each do |c| %>
<%= link_to c.name, category_path(c) %><br>
<% c.foods.each do |f|%>
<%= link_to image_tag(f.image), food_path(f) %><br>
<% end %>
<% end %>

app/views/categories/new.erb
<h1>Create a Category</h1>

<%= form_for @category do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/show.erb
<h1><%= @category.name %></h1>
<% @category.foods.each do |f| %>
<%= link_to image_tag(f.image), food_path(f) %>
<% end %>

app/views/foods/edit.erb
<div class="ui raised very padded text container segment">

<h1><%= "Edit #{@food.name}"%></h1>

<%= form_for @food, html: {class: 'ui form'} do |f| %>
<div class="field">
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :spot_name %>
<%= f.text_field :spot_name %>
</div>
<div class="field">
<%= f.label :address %>
<%= f.text_field :address %>
</div>
<div class="field">
<%= f.label :category %>
<%= f.collection_select :category_id, @categories, :id, :name, prompt: true %>
</div>
<div class="field">
<%= f.label :location %>
<%= f.collection_select :location_id, @locations, :id, :city, prompt: true %>
</div>
<div class="field">
<%= f.label :image %>
<%= f.file_field :image %>
<%= f.hidden_field(:food_id, :value => @food.id)%>
</div>
<%= f.submit class: 'ui black button' %>
<% end %>

</div>

app/views/foods/index.erb
<div class="foods-wrapper">
  <h3>Get Some Junk in Yo Trunk!</h3>

  <%= form_tag(foods_path, method: :get, class: 'ui form') do %>
  <div class="inline field">
    <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag ("Search Foods"), class: 'ui black button' %>
  </div>

  <% end %>
</div>

  <div class="ui grid container">
    <% @foods.each do |f| %>
      <div class="four wide column">
        <%= link_to(image_tag(f.image, class: "food-image"), food_path(f)) %>
      </div>
    <% end %>
  </div>

app/views/foods/new.erb
<div class="ui raised very padded text container segment">

<h1>Create a Food</h1>

<%= form_for @food, html: {class: 'ui form'} do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :spot_name %>
  <%= f.text_field :spot_name %>
  </div>
  <div class="field">
  <%= f.label :address %>
  <%= f.text_field :address %>
  </div>
  <div class="field">
  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :name, prompt: true %>
  </div>
  <div class="field">
  <%= f.label :location %>
  <%= f.collection_select :location_id, @locations, :id, :city, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.hidden_field(:food_id, :value => @food.id)%>
  </div>
  <%= f.submit class: 'ui black button' %>
<% end %>

app/views/foods/show.erb
<div class="food-container">
  <%= image_tag @food.image, class: 'food-show-image' %>
  <h1><%= @food.name %></h1>
  <p>Avg Rating: 4.7</p>
  <span class="spot_name"><%= @food.spot_name %></span><br>
  <span class="address"><%= @food.address %></span>
  <%= button_to "Edit #{@food.name}", edit_food_path(@food), method: 'get', class: 'ui black button mini' %>
  <%= button_to "Add a Review", new_food_review_path(@food), method: 'get', class: 'ui black button mini' %>
</div>



<div class='ui cards container'>
  <% @food.reviews.each do |r| %>
    <div class="ui raised link card">
      <div class="content">
        <div class="header"><%= link_to r.title, review_path(r) %></div>
        <div class="meta">
          <span class="category"><%= r.rating %></span>
        </div>
        <div class="description">
          <p><%= r.content %></p>
        </div>
      </div>
      <div class="extra content">
        <div class="right floated">
          <%= r.foodie.username %>
        </div>
      </div>
    </div>
  <% end %>